### PR TITLE
Build Fixes from PR #765

### PR DESCRIPTION
**Pull request by carolynvs**
PR #765 didn't get a clean build before merging. This fixes the build on master by
* syncs the vendor directory with Gopkg.lock
* makes the linter happy
* uses only go 1.11 string functions

### CODE REVIEW

**Comment by silvin-lubecki** [comment]
Tests are failing:
```
pkg/driver/kubernetes.go:353:10: undefined: strings.ReplaceAll
```

**Comment by glyn** [comment]
> Tests are failing:
> 
> ```
> pkg/driver/kubernetes.go:353:10: undefined: strings.ReplaceAll
> ```

That's why https://github.com/deislabs/duffle/pull/774 bumps Go to 1.12.

**Comment by carolynvs** [comment]
Sorry I'm aware, just in a meeting. Will fix in an hour.

**Comment by carolynvs** [comment]
@glyn I was hoping to just fix the build and let the go bumping happen in your PR (which looks great). I am 100% on board with switching to a better base image. I just wanted to focus on the changes that should have been in that PR to begin with, and not smoosh too many things together into this PR.

**Comment by carolynvs** [comment]
I updated the title of the PR to better reflect what all ended up in this grab bag PR. 😀

**Comment by technosophos** [comment]
@glyn Since this one does not require 1.12, can you re-review this one and see if we can get it in to quickly get things green again?

**Comment by technosophos** [comment]
Okay. Since we've got a broken master right now, let's get this one merged, then start working on the 1.12 as a follow-up.
